import type { Metadata } from "next";

import localFont from 'next/font/local'

import "./globals.css";
import { NavbarDemo } from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const helvetica = localFont({
  src: [
    {
      path: '../font/HelveticaNeueLight.otf',
      weight: '300',
      style: 'light',
    },
    {
      path: '../font/HelveticaNeueRoman.otf',
      weight: '400',
      style: 'normal',
    },

    {
      path: '../font/HelveticaNeueMedium.otf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../font/HelveticaNeueBold.otf',
      weight: '700',
      style: ' bold',
    },
  ],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={helvetica.className}>{children}</body>
    </html>
  );
}
